name: derry
description: A script manager to help you define script shortcuts and use them
  effortlessly, and performantly.
version: 1.2.1
repository: https://github.com/frencojobs/derry

environment:
  sdk: '>=2.12.0 <3.0.0'

executables:
  derry:

dependencies:
  args: ^2.0.0
  console: ^4.0.0
  equatable: ^2.0.0
  ffi: ^1.0.0
  path: ^1.8.0
  string_similarity: ^2.0.0
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^1.11.5
  build_version: ^2.0.1
  import_sorter: ^4.4.1
  lint: ^1.5.3
  test: ^1.6.0

scripts: derry.yaml

import_sorter:
  comments: false
